// Demo data served to the 'demo' user when no database is available

export const DEMO_USER_ID = 'demo'

export const DEMO_PROFILE = {
  id: 'demo',
  email: 'demo@samarketplace.co.za',
  name: 'Thandi Dlamini',
  username: 'demo',
  phone: '+27 82 000 0000',
  businessName: "Thandi's Sneaker Empire",
  whatsapp: '27820000000',
  instagramHandle: '@thandisneakers',
  tiktokHandle: '@thandisneakers_za',
}

export const DEMO_PRODUCTS = [
  {
    id: 'demo-prod-1',
    name: 'Nike Air Force 1 Low',
    description: 'Classic white leather sneakers. Authentic, deadstock condition.',
    price: 1899,
    originalPrice: 2199,
    category: 'Sneakers',
    sizes: ['7', '8', '9', '10', '11'],
    stockQuantity: 5,
    isVisible: true,
    images: [],
    sellerId: 'demo',
    createdAt: new Date('2026-02-01').toISOString(),
    updatedAt: new Date('2026-02-01').toISOString(),
  },
  {
    id: 'demo-prod-2',
    name: 'Jordan 1 Retro High OG',
    description: 'Iconic silhouette in Chicago colourway. Brand new with box.',
    price: 3499,
    originalPrice: null,
    category: 'Sneakers',
    sizes: ['8', '9', '10'],
    stockQuantity: 2,
    isVisible: true,
    images: [],
    sellerId: 'demo',
    createdAt: new Date('2026-02-10').toISOString(),
    updatedAt: new Date('2026-02-10').toISOString(),
  },
  {
    id: 'demo-prod-3',
    name: 'Adidas Yeezy Boost 350',
    description: 'Authentic Cinder colourway. Perfect for everyday wear.',
    price: 4200,
    originalPrice: 4800,
    category: 'Sneakers',
    sizes: ['8', '9', '10', '11'],
    stockQuantity: 3,
    isVisible: false,
    images: [],
    sellerId: 'demo',
    createdAt: new Date('2026-02-15').toISOString(),
    updatedAt: new Date('2026-02-15').toISOString(),
  },
]

export const DEMO_ORDERS = [
  {
    id: 'demo-order-1',
    customerName: 'Sipho Nkosi',
    customerPhone: '+27 71 234 5678',
    productName: 'Nike Air Force 1 Low',
    size: '9',
    price: 1899,
    deliveryAddress: '123 Main St, Soweto, Johannesburg',
    status: 'delivered',
    paid: true,
    notes: null,
    courierName: 'The Courier Guy',
    trackingNumber: 'TCG-12345',
    sellerId: 'demo',
    createdAt: new Date('2026-02-05').toISOString(),
    updatedAt: new Date('2026-02-08').toISOString(),
  },
  {
    id: 'demo-order-2',
    customerName: 'Nomsa Mahlangu',
    customerPhone: '+27 82 345 6789',
    productName: 'Jordan 1 Retro High OG',
    size: '8',
    price: 3499,
    deliveryAddress: '45 Bree St, Cape Town',
    status: 'shipped',
    paid: true,
    notes: 'Please leave at the gate',
    courierName: 'Postnet',
    trackingNumber: 'PN-67890',
    sellerId: 'demo',
    createdAt: new Date('2026-02-18').toISOString(),
    updatedAt: new Date('2026-02-20').toISOString(),
  },
  {
    id: 'demo-order-3',
    customerName: 'Kagiso Sithole',
    customerPhone: '+27 63 456 7890',
    productName: 'Adidas Yeezy Boost 350',
    size: '10',
    price: 4200,
    deliveryAddress: '789 Pritchard St, Johannesburg',
    status: 'pending',
    paid: false,
    notes: null,
    courierName: null,
    trackingNumber: null,
    sellerId: 'demo',
    createdAt: new Date('2026-02-24').toISOString(),
    updatedAt: new Date('2026-02-24').toISOString(),
  },
]
